config/routes.rb
PreventIT::Application.routes.draw do
  get "password_resets/new"

  # get 'doctors/new', to: 'users#new_doctor'
#   post 'doctors', to: 'users#create_doctor'

  resources :doctors

  get '/search' => 'pages#new', as: 'new_search'
  get '/search/patients' => 'pages#search_patients', as: 'patient_search'
  get '/search/diagnoses' => 'pages#search_diagnoses', as: 'diagnoses_search'
  get '/search/medications' => 'pages#search_medications', as: 'medications_search'
  get '/search/full_medications' => 'pages#search_full_medications', as: 'full_medications_search'
  # get '/med_init_selection' => 'pages#init_selection', as: 'medication_init'
  get 'alerts/completed' => 'alerts#completed', as: 'alerts_completed'

  resources :alerts, only: [:index, :edit, :update, :show]
  resources :appointment_types

  put 'alert/:id/complete' => 'alerts#mark_complete', as: 'alert_complete'

  get 'users/:user_id/reminders/completed' => 'reminders#completed', as: 'reminders_completed'
  get 'users/:user_id/reminders/upcoming' => 'reminders#upcoming', as: 'reminders_upcoming'
  
  
  resources :users, only: [:create, :new, :destroy, :show, :edit, :update] do
    resources :reminders
    resources :diagnoses
    resources :appointments
    get 'add_diagnosis' => 'diagnoses#add_diagnosis', as: 'add_diagnosis'
    get :activate, on: :collection
    get :password_reset, on: :collection
    put :password_update, on: :collection
    resources :medications
    resources :symptoms do
      resources :reminders, controller: :reminders, only: [:new, :create, :index]
    end
  end
  
  resource :session, only: [:create, :destroy, :new]
  resources :password_resets, only: [:new, :edit, :update, :create]
  get '/auth/google_oauth2/callback' => 'sessions#create'

  root to: "sessions#new"
end

app/models/reminder.rb
# == Schema Information
#
# Table name: reminders
#
#  id              :integer          not null, primary key
#  datetime        :datetime         not null
#  title           :string(255)      not null
#  input           :integer
#  patient_id      :integer          not null
#  due             :boolean          default(FALSE), not null
#  note            :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  checked         :boolean          default(FALSE), not null
#  complete        :boolean
#  sub_type        :string(255)
#  input_checked   :boolean          default(FALSE), not null
#  remindable_id   :integer
#  remindable_type :string(255)
#  parent_id       :integer          default(0), not null
#

class Reminder < ActiveRecord::Base
  DAY_STRINGS =
    ["Sunday",
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday"]
      
  REMINDABLE_TYPES =
    ["Appointment",
      "Medication",
      "Treatment",
      "Input",
      "Symptom",
      "Other"]

  attr_accessible :datetime, :title, :remindable_type, :remindable, :patient_id, :note, :complete, :input, :sub_type, :input_checked, :patient, :parent

  validates :datetime, presence: true
  validates :remindable_type, presence: true, inclusion: { in: Reminder::REMINDABLE_TYPES, message: "Invalid type" }
  validates :title, :patient, presence: true

  before_validation :ensure_valid_remindable_type

  belongs_to(
    :remindable,
    polymorphic: true,
    foreign_key: :remindable_id,
    primary_key: :id,
    inverse_of: :reminders
  )

  belongs_to(
    :patient,
    class_name: "User",
    foreign_key: :patient_id,
    primary_key: :id,
    inverse_of: :reminders
  )
  
  belongs_to(
    :parent,
    class_name: "Reminder",
    foreign_key: :parent_id,
    primary_key: :id,
    inverse_of: :children
  )

  has_many(
    :children,
    class_name: "Reminder",
    foreign_key: :parent_id,
    primary_key: :id,
    inverse_of: :parent,
    dependent: :destroy
  )
  
  
  ############ Class Methods #################
  ###############################################
  
  def self.day_strings
    self::DAY_STRINGS
  end
  
  def self.remindable_types
    self::REMINDABLE_TYPES
  end
  
  
  # marks all reminders due (if their time is past)
  def self.mark_all_due
    @all_not_due_reminders = self.all_not_due
    @all_not_due_reminders.each do |reminder|
      if reminder.is_due?
        reminder.mark_due!
        reminder.self_propagation! unless (reminder.remindable_type == "Appointment")
      end
    end

    nil
  end

  # returns all reminders marked as not due
  def self.all_not_due
    self.find_all_by_due(false)
  end
  
  # Factory method returning a reminder given an associated appointment
  def self.create_appt_reminder(appt)
    reminder = appt.reminders.create({
            datetime: appt.datetime,
            title: "#{appt.appointment_type.name} appointment w/ #{appt.doctor.doctor_full_name}",
            patient_id: appt.patient_id,
            sub_type: appt.appointment_type.name
          })
    
  end

  # Returns true if the reminder's time is passed in the current day
  # AND generates and new reminder if it's due for the 1st time
  # def mark_due
 #    if is_due?
 #      self.reminder_self_propogation
 #    end
 #  end

  
 ############ Instance Methods #################
 ###############################################
 
 def ensure_valid_remindable_type
   self.remindable_type = "Other" unless Reminder::REMINDABLE_TYPES.include?(self.remindable_type)
   self.remindable_id = nil if self.remindable_type == "Other"
 end
 
 # Returns true / false if the reminder is due
  def is_due?
    self.datetime.past?
  end

  # def should_check_for_alert
#     self.is_due? &&
#   end


  ## OLD WAY
  # generates a new reminder with the same parameters 1 yr in the future
  # def self_propagation!
 # 
 #    # if (!self.due && self.datetime.past?)
 # #      self.add_new_reminder_year!
 # #    end
 # 
 #    patient_user = self.patient
 #    new_attributes = self.attributes.except("id",
 #      "complete",
 #      "input",
 #      "due",
 #      "created_at",
 #      "updated_at"
 #      )
 # 
 #    new_rem = patient_user.reminders.build(new_attributes)
 #    new_rem.datetime = new_rem.datetime.advance(days: 7*12)
 # 
 #    patient_user.save
 # 
 #    self.mark_due!
 #  end

 # generates a new reminder with the same parameters 1 yr in the future
  def self_propagation!
    new_rem = self.self_propagation
    new_rem.save

    new_rem
  end
  
  def self_propagation
    remindable = self.remindable
    new_attributes = self.attributes.except("id",
      "complete",
      "input",
      "due",
      "created_at",
      "updated_at",
      "remindable_id",
      "checked",
      "parent_id"
    )

    new_rem = remindable.reminders.build(new_attributes)
    new_rem.parent = self
    new_rem.datetime = new_rem.datetime.advance(weeks: 12)
    
    new_rem
  end

  # Returns the day of the week in which the reminder is due corrected for the patient's timezone.
  def day_str(timezone = patient.timezone)
    parsed_time(timezone).strftime("%A")
  end
  
  # Returns the day of the week in which the reminder is due in UTC
  def utc_day_str
    self.datetime.strftime("%A")
  end

  # marks the reminder as due and saves. Returns true / false if it saved
  def mark_due!
    self.due = true
    self.save
  end

  # returns a string of the reduced amount the reminder is overdue by
  def overdue_by_str
    "#{self.overdue_by} #{@overdue_str}"
  end

  # returns the lowest denomination of how much it's overdue
  def overdue_by
    @overdue_str = "minutes"
    
    overdue = (((self.is_due?) ? (Time.zone.now - self.datetime) : (self.datetime - Time.zone.now)) / 60).to_i 

    if overdue > 60
      overdue /=  60
      @overdue_str = "hours"
      if overdue > 24
        overdue /= 24
        @overdue_str = "days"
        if overdue > 7
          overdue /= 7
          @overdue_str = "weeks"
          if overdue > 4
            overdue /= 4
            @overdue_str = "months"
          end
        end
      end
    end
    
    @overdue_str = @overdue_str[0..-2] if overdue == 1
    
    overdue
  end
  
  
  
  # returns the datetime converted in the provided timezone or patient's timezone by default.
  def parsed_time(timezone = patient.timezone)
    self.datetime.in_time_zone(timezone)
  end


  # def mark_complete(is_complete)
#     self.complete = is_complete
#     self.add_new_reminder_year!
#   end

end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_filter :require_signed_in!
  before_filter :require_authority!
  before_filter :set_timezone, only: [:create, :update]

  def index
    @user = User.find(params[:user_id])
    @reminders = @user.incomplete_due_reminders.order(:datetime).page(params[:page]).per(20)
  end

  def completed
    @user = User.find(params[:user_id])
    @reminders = @user.reminders.where(complete: true).order(:datetime).page(params[:page]).per(20)
    
    render :index
  end
  
  def upcoming
    @user = User.find(params[:user_id])
    @reminders = @user.upcoming_reminders.order(:datetime).page(params[:page]).per(20)
    
    render :index
  end

  def new
    @user = User.find(params[:user_id])
    @remindable = find_remindable
    @reminder = @user.reminders.build(remindable: @remindable)
    @days = []
    @times = []
    
    
    respond_to do |format|
      format.html { render :new }
      format.js
      
      # if @remindable
 #        render :form
 #      else
 #
 #      end
    end
  end

  # Creates (x = 12 weeks worth of reminders for each day / time combination.
  # Corresponds with reminder self propagation.
  # TODO Refactor into helper methods.
  def create
    @reminders = []
    @parent_reminders = []
    @remindable = params[:remindable][:remindable_type] != "Other" && params[:remindable][:remindable_type].classify.constantize.where(patient_id: @user.id).find(params[:remindable][:remindable_id])
    @days = params[:days] || []
    @times = params[:times].reject { |time| time.blank? }
    today_str = Time.zone.now.strftime("%A")
    
    # should be helper method
    @days.each do |day|
      @times.each do |time|
        new_time = (today_str == day) ? Chronic.parse("today at #{time}") : Chronic.parse("next #{day} at #{time}")
        new_time = new_time.advance(weeks: 1) if (new_time.past?) 
        
        @reminder = @user.reminders.build(params[:reminder]) 
        if @remindable
          @reminder.remindable = @remindable
        else
          @reminder.remindable_type =  params[:remindable][:remindable_type]
        end
        @reminder.datetime = new_time
        @reminders << @reminder
        @parent_reminders << @reminder
        
        11.times do |x|
          new_rem = @user.reminders.build(params[:reminder])
          
          # Advancing the datetime returns a new datetime and doesn't mutate original
          new_rem.datetime = @reminder.datetime.advance(weeks: x + 1)
          new_rem.remindable = @remindable
          new_rem.parent = @reminders.last
          
          @reminders << new_rem
        end
      end
    end
    
    respond_to do |format|
      if @user.save 
        format.html {
          flash[:notices] = ["Reminder created!"]
          
          if (@remindable)
            redirect_to polymorphic_url([@user, @remindable, :reminders])
          else
            redirect_to user_reminders_url(@user)
          end
        }
        format.js { flash.now[:notices] = ["Reminder created!"]}
      else
        flash.now[:errors] = @user.reminders.map(&:errors).map(&:full_messages).select { |el| !el.empty? }
        # flash.now[:errors] << "At least 1 days / time must be picked!" if num_reminders_created == 0
        format.html { render :new }
        format.js { render :new }
      end
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @reminder = @user.reminders.find(params[:id])
  end

  def update
    @reminder = Reminder.find(params[:id])

    if @reminder.update_attributes(params[:reminder])
      flash.now[:notices] = ["Reminder updated!"]
      redirect_to user_reminders_url(params[:user_id])
    else
      flash.now[:errors] = @reminder.errors.full_messages
      render :edit
    end
  end
  
  private
  
  def find_remindable(hash = params)
    hash.each do |name, value|
      if name =~ /(.+)_id$/
        next if $1 == "user"
        return $1.classify.constantize.where(patient_id: params[:user_id]).find(value)
      end
    end
    nil
  end
  
  # def create_remindable
 #    @remindable = find_remindable
 #    @reminder = @remindable.reminders.create(params[:reminder])
 #  end
  
  # def show
#     @user = User.find(params[:user_id])
#     @reminder = Reminder.find(params[:id])
#   end


  # def destroy
#
#   end
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/views/reminders/_form.html.erb
<% @remindable = remindable %>
<% form_url = (remindable) ? polymorphic_url([user, remindable, :reminders]) : user_reminders_url(user) %>

<form class="form" <%= "data-remote='true'" unless request.format == "text/html" %> action="<%= form_url %>" method="POST">
  <h3>New <%= remindable.class if remindable %> Reminder:</h3>
  <%= auth_token %>
  <%= "<input type='hidden' name='_method' value='PUT'>".html_safe if reminder.persisted? %>
  
  <div class="input">
    <label for="title">Title:</label>
    <input
      id="title"
      type="text"
      name="reminder[title]"
      value="<%= reminder.title %>">
  </div>

  <div class="input">
    <label for="remindable-type-select">Type:</label>
    <select id="remindable-type-select" name="remindable[remindable_type]" data-user_id="<%= user.id %>">
      <option></option>
      <% selected = false %>
      <% Reminder::REMINDABLE_TYPES.each do |remindable_type|%>
        <% selected = true if (remindable && remindable_type == remindable.class.to_s) || (!remindable && remindable_type == "Other") %>
        <option <%= "selected" if selected %> value="<%= remindable_type %>"><%= remindable_type %></option>
        <% selected = false %>
      <% end %>
    </select>
  </div>

  <div class="input">
    <label for="remindable-select">Pick one:</label>
    <select
      <%= "disabled" unless remindable  %>
      id="remindable-select"
      name="remindable[remindable_id]"
      class="">
      <option></option>
      <option <%= "selected" if remindable %> value="<%= remindable.id if remindable %>"><%= remindable.name if remindable %></option>
    </select>
  </div>
  
  <div class="checkbox-group">
    
    <h4>Day(s):</h4>
    <div class="checkbox-input">
      <label for="sunday">Su</label>
      <input
        <%= "checked" if days && @days.include?("0") %>
        id="sunday"
        type="checkbox"
        name="days[]"
        value="Sunday">
    </div>

    <div class="checkbox-input">
      <label for="monday">M</label>
      <input
        <%= "checked" if days && days.include?("1") %>
        id="monday"
        type="checkbox"
        name="days[]"
        value="Monday">
    </div>

    <div class="checkbox-input">
      <label for="tuesday">T</label>
      <input
        <%= "checked" if days && days.include?("2") %>
        id="tuesday"
        type="checkbox"
        name="days[]"
        value="Tuesday">
    </div>

    <div class="checkbox-input">
      <label for="wednesday">W</label>
      <input
        <%= "checked" if days && days.include?("3") %>
        id="wednesday"
        type="checkbox"
        name="days[]"
        value="Wednesday">
    </div>

    <div class="checkbox-input">
      <label for="thursday">Th</label>
      <input
        <%= "checked" if days && days.include?("4") %>
        id="thursday"
        type="checkbox"
        name="days[]"
        value="Thursday">
    </div>

    <div class="checkbox-input">
      <label for="friday">F</label>
      <input
        <%= "checked" if days && days.include?("5") %>
        id="friday"
        type="checkbox"
        name="days[]"
        value="Friday">
    </div>

    <div class="checkbox-input">
      <label for="saturday">S</label>
      <input
        <%= "checked" if days && days.include?("6") %>
        id="saturday"
        type="checkbox"
        name="days[]"
        value="Saturday">
    </div>
  </div>

  <div class="time-input time-group">
 
    <div class="plus group" id="plus">
      <a href="#"></a>      
    </div>
          
    <% if !times || times.empty? %>
      <label for="1">Time 1 :</label>
      <input
        id="1"
        type="time"
        name="times[]"
        value="<%= times.first if times %>">
    <% else %>
      <% times.each_with_index do |time, i| %>
        <label for="<%= i+1 %>">Time <%= i+1 %>:</label>
        <input
          id="<%= i+1 %>"
          type="time"
          name="times[]"
          value="<%= time %>">
      <% end %>
    <% end %>
  
  </div>

  <div class="submit">
    <input type="submit" value="Add Reminder">
  </div>
</form>

<% content_for :js do %>
  <script type="text/javascript">
    $(document).on("page:change", function() {
      
    });
    // $remindableTypeSelect.select2({
//       placeholder: "Enter a name..",
//       allowClear: true,
//       minimumInputLength: 2,
//       formatSelection: function(data) {
//         return data.text;
//       },
//       ajax: {
//         url: '<%= medications_search_url %>',
//         dataType: 'json',
//         data: function (term, page) {
//           return {
//             query: term
//           };
//         },
//         results: function(data, page) {
//           var results = [];
//           $.each(data, function(index, item){
//             results.push({id: item, text: item});
//           });
//           return {results: results};
//         }
//       },
//       initSelection : function (element, callback) {
//         var name = $remindableTypeSelect.val();
//         var data = {id: name, text: name};
//         callback(data);
//       }
//     });

  </script>
<% end %>

app/views/reminders/_li.html.erb
<tr>
  <td><%= reminder.parsed_time.to_s(:date) %></td>
  <td><%= reminder.parsed_time.to_s(:time_12hr) %></td>
  <td class="<%= 'overdue' if reminder.is_due? %>"><%= reminder.overdue_by_str %></td>
  <td><%= link_to reminder.title, edit_user_reminder_url(reminder.patient_id, reminder) %></td>
  <% if reminder.remindable_id %>
    <td><%= link_to reminder.remindable_type, polymorphic_url([user, reminder.remindable], action: :edit) %></td>
  <% else %>
    <td><%= reminder.remindable_type %></td>
  <% end %>
</tr>

app/views/reminders/_list.html.erb
<div class="reminders-table">
  <table id="reminders">
    <thead>
      <div class="group" id="reminder-plus">
        <% url_params = (remindable) ? {remindable_type: remindable.class, remindable_id: remindable.id} : {} %>
        <a class="reminder-plus" data-remote="true" href="<%= polymorphic_url([user, remindable, :reminder], action: :new) %>"></a>      
      </div>

      <label class="table-label" for="reminders"><%= title %></label>
      <tr>
        <th>Due Date</th>
        <th>Time</th>
        <th><%= ((!reminders.empty? && reminders.first.is_due?)) ? "Overdue By" : "Due In" %></th>
        <th>Title</th>
        <th>Type</th>
      </tr>
    </thead>

    <% reminders.each do |reminder| %>
      <%= render "reminders/li", reminder: reminder, user: user  %>
    <% end %>

  </table>
</div>

app/views/reminders/_remindable_index.html.erb
Remindable Index

app/views/reminders/create.js.erb
<% if @reminder.persisted? %>
  $('#reminders').append("<%= escape_javascript(render 'reminders/li', user: @user, reminder: @reminder) %>");
<% end %>

var flashError = "<%= flash[:errors].join('<br>').html_safe if flash[:errors] %>";
var flashNotice = "<%= flash[:notices].join('<br>').html_safe if flash[:notices] %>";
window.modal.hide();

app/views/reminders/edit.html.erb
<%= render "users/sub_bar", user: @user%>


<main class="group">
  <div class="side-content">
    <div class="title">
      <h3>Reminders</h3>
    </div>
    
    <div class="side-info">
		<ul>
	  	  <li><%= link_to "New Reminder", new_user_reminder_url(@user) %></li>
	  		<li><%= link_to "Complete Reminders", reminders_completed_url(@user) %></li>
	  		<li><%= link_to "Due Reminders", user_reminders_url(@user) %></li>
        <li><%= link_to "Upcoming Reminders", reminders_upcoming_url(@user) %></li>
		</ul>
    </div>
  </div>

  <div class="sub-content">
    
    <form class="form" action="<%= user_reminder_url(@reminder.patient_id, @reminder) %>" method="POST">

      <h3>Title: <%= @reminder.title %></h3>

      <input type="hidden" name="_method" value="PUT">

      <%= auth_token %>

      <div class="input">
        <label for="input">Inpute Value:</label>
        <input type="number"
          id="input"
          name="reminder[input]"
          min="0.00"
          step="0.1"
          value="<%= @reminder.input %>">
      </div>


      <div class="input">
        <label for="note">Enter a Note:</label>
        <textarea id="note" name="reminder[note]"><%= @reminder.note %></textarea>
      </div>


      <div class="radio-group group">
        <p>Did you complete your task?</p>
        <div class="radio-input">
          <label for="complete">Yes</label>
          <input id="complete" <%= 'checked' if @reminder.complete %> type="radio" name="reminder[complete]" value="true">
        </div>

        <div class="radio-input">
          <label for="incomplete">No</label>
          <input id="incomplete" <%= 'checked' unless @reminder.complete %> type="radio" name="reminder[complete]" value="false">
        </div>
      </div>

      <div class="submit long-submit">
        <input type="submit" value="Save">
      </div>
    </form>
  </div>
</main>

app/views/reminders/index.html.erb
<%= render "users/sub_bar", user: @user%>


<main class="group">

  <div class="side-content">
    <div class="title">
      <h3>Reminders:</h3>
    </div>

    <div class="side-info">
		<ul>
	  	  <li><%= link_to "New Reminder", new_user_reminder_url(@user) %></li>
	  		<li><%= link_to "Complete Reminders", reminders_completed_url(@user) %></li>
	  		<li><%= link_to "Due Reminders", user_reminders_url(@user) %></li>
        <li><%= link_to "Upcoming Reminders", reminders_upcoming_url(@user) %></li>
		</ul>
    </div>
  </div>

  <div class="sub-content">

    <label for="reminders" class="table-label"><%= (params[:action] == "completed") ? "Completed" : "Due" %> Reminders:</label>
    <%= render "list", reminders: @reminders, user: @user, remindable: nil, title: "Reminders" %>
    <p><%= paginate @reminders %></p>
  </div>
</main>

app/views/reminders/new.html.erb
<%= render "users/sub_bar", user: @user%>


<main class="group">
  <div class="side-content">
    <div class="title">
      <h3>New Reminder</h3>
    </div>
    
    <div class="side-info">
		<ul>
	  	  <li><%= link_to "New Reminder", new_user_reminder_url(@user) %></li>
	  		<li><%= link_to "Complete Reminders", reminders_completed_url(@user) %></li>
	  		<li><%= link_to "Due Reminders", user_reminders_url(@user) %></li>
        <li><%= link_to "Upcoming Reminders", reminders_upcoming_url(@user) %></li>
		</ul>
    </div>
  </div>

  <div class="sub-content">
    <%= render "form", user: @user, reminder: @reminder, remindable: @remindable, times: @times, days: @days %>
  </div>
</main>

app/views/reminders/new.js.erb
window.modal.swapContent("<%= escape_javascript(render partial: 'form', locals: { user: @user, remindable: @remindable, reminder: @reminder, times: @times, days: @days})%>");

var $remindableTypeSelect = $('#remindable-type-select');

$remindableTypeSelect.select2({
  placeholder: "Enter a name..",
  allowClear: true,
  formatSelection: function(data) {
    return data.text;
  }
});


var $remindableSelect = $('#remindable-select');

$remindableSelect.select2({
  placeholder: "Pick one",
  allowClear: true,
  enable: false
});


$remindableTypeSelect.on('change', function(event) {
  var url = "/users/<%= @user.id %>/" + event.currentTarget.value.toLowerCase() + "s";
  
  var placeHolder;
  
  $.ajax(url, {
    dataType: "json",
    data: function (term, page) { // page is the one-based page number tracked by Select2
      return {
        q: term, //search term
        page_limit: 10, // page size
        page: page, // page number
        apikey: "ju6z9mjyajq2djue3gbvv26t" // please do not use so this example keeps working
      };
    },
    success: function(data) {
      console.log("In remindableSelectAjax success");
      console.log(data);
      var html = "<option></option>";
      
      $.each(data, function(i, el) {
        html += ("<option class='unique-choice' value='" + el.id + "'>" + el.name +"</option>");
      });
      
      $remindableSelect.html(html);
      $remindableSelect.select2('enable', true);
      $remindableSelect.select2('open', true);
    },
    error: function() {
      console.log("Error in remindable search!");
    }
  });
}); 

$('select#remindable-type-select2').select2({
  placeholder: "Select Type..",
  allowClear: true
});