config/routes.rb
PreventIT::Application.routes.draw do
  get "password_resets/new"

  # get 'doctors/new', to: 'users#new_doctor'
#   post 'doctors', to: 'users#create_doctor'

  resources :doctors

  get '/search' => 'pages#new', as: 'new_search'
  get '/search/patients' => 'pages#search_patients', as: 'patient_search'
  get '/search/diagnoses' => 'pages#search_diagnoses', as: 'diagnoses_search'
  get '/search/medications' => 'pages#search_medications', as: 'medications_search'
  get '/search/full_medications' => 'pages#search_full_medications', as: 'full_medications_search'
  # get '/med_init_selection' => 'pages#init_selection', as: 'medication_init'
  get 'alerts/completed' => 'alerts#completed', as: 'alerts_completed'

  resources :alerts, only: [:index, :edit, :update, :show]
  resources :appointment_types

  put 'alert/:id/complete' => 'alerts#mark_complete', as: 'alert_complete'

  get 'users/:user_id/reminders/completed' => 'reminders#completed', as: 'reminders_completed'
  get 'users/:user_id/reminders/upcoming' => 'reminders#upcoming', as: 'reminders_upcoming'
  
  
  resources :users, only: [:create, :new, :destroy, :show, :edit, :update] do
    resources :reminders
    resources :diagnoses
    resources :appointments
    get 'add_diagnosis' => 'diagnoses#add_diagnosis', as: 'add_diagnosis'
    get :activate, on: :collection
    get :password_reset, on: :collection
    put :password_update, on: :collection
    resources :medications
    resources :symptoms do
      resources :reminders, controller: :reminders, only: [:new, :create, :index]
    end
  end
  
  resource :session, only: [:create, :destroy, :new]
  resources :password_resets, only: [:new, :edit, :update, :create]
  get '/auth/google_oauth2/callback' => 'sessions#create'

  root to: "sessions#new"
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      not null
#  password_digest        :string(255)      not null
#  session_token          :string(255)      not null
#  first_name             :string(255)
#  last_name              :string(255)
#  phone                  :string(255)
#  doctor_id              :integer
#  practice_id            :integer
#  is_doctor              :boolean          default(FALSE), not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  avatar_file_name       :string(255)
#  avatar_content_type    :string(255)
#  avatar_file_size       :integer
#  avatar_updated_at      :datetime
#  email_notifications    :boolean          default(TRUE), not null
#  uid                    :string(255)
#  access_token           :string(255)
#  provider               :string(255)
#  active                 :boolean          default(FALSE), not null
#  activation_token       :string(255)      default("INACTIVE"), not null
#  timezone               :string(255)      default("Eastern Time (US & Canada)"), not null
#  password_reset_token   :string(255)
#  password_reset_sent_at :datetime
#

class User < ActiveRecord::Base
  attr_accessible :email, :password, :first_name, :last_name, :phone, :avatar,
    :email_notifications, :timezone,
    :uid, :access_token, :provider
  attr_reader :password

  validates :email, presence: true, uniqueness: true
  validates :password_digest, :timezone, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}
  validates :session_token, presence: true, uniqueness: true
  validates :uid, uniqueness: {scope: :provider, if: :check_uid_by_provider}
  validates_inclusion_of :timezone, in: ActiveSupport::TimeZone.zones_map(&:name)

  paginates_per 10

  before_validation :ensure_session_token
  before_create :set_activation_token
  
  has_attached_file :avatar, :styles => {
         :big => "600x600>",
         :small => "100x100>"
       },
       :default_url => "/assets/small/missing.png"

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  include PgSearch
  pg_search_scope :search_on_name,
                  against: [:first_name, :last_name],
                  using: {
                    :trigram => {
                      :threshold => 0.03
                    }
                  }


  #### Patient Associations ####
  
  # A Patient should really only have 1 instance of health 
  has_many(
    :health,
    class_name: "Health",
    foreign_key: :patient_id,
    primary_key: :id,
    inverse_of: :patient,
    dependent: :destroy
  )

  belongs_to(
    :doctor,
    class_name: "User",
    foreign_key: :doctor_id,
    primary_key: :id
  )

  has_one(
    :practice,
    through: :doctor,
    source: :practice
  )

  has_many(
    :reminders,
    class_name: "Reminder",
    foreign_key: :patient_id,
    primary_key: :id,
    inverse_of: :patient
  )

  has_many(
    :alerts,
    class_name: "Alert",
    foreign_key: :patient_id,
    primary_key: :id,
    inverse_of: :patient,
    dependent: :destroy
  )

  has_many(
    :patient_diagnoses,
    class_name: "PatientDiagnosis",
    foreign_key: :patient_id,
    primary_key: :id,
    inverse_of: :patient
  )

  has_many(
    :diagnoses,
    through: :patient_diagnoses,
    source: :diagnosis
  )

  has_many(
    :appointments,
    class_name: "Appointment",
    foreign_key: :patient_id,
    primary_key: :id,
    inverse_of: :patient,
    dependent: :destroy
  )

  has_many(
    :appt_types,
    through: :diagnoses,
    source: :appt_types,
    uniq: true
  )
    
  has_many(
    :patient_medications,
    class_name: "PatientMedication",
    foreign_key: :patient_id,
    primary_key: :id,
    inverse_of: :patient
  )
  
  has_many(
    :symptoms,
    class_name: "Symptom",
    primary_key: :id,
    foreign_key: :patient_id,
    inverse_of: :patient
  )

  #### Doctor Associations ####

  belongs_to(
    :practice,
    class_name: "Practice",
    foreign_key: :practice_id,
    primary_key: :id,
    inverse_of: :doctors
  )

  has_many(
    :patients,
    class_name: "User",
    foreign_key: :doctor_id,
    primary_key: :id
  )

  has_many(
    :patient_alerts,
    through: :patients,
    source: :alerts
  )

  has_many(
      :alert_setting,
      class_name: "AlertSetting",
      foreign_key: :doctor_id,
      primary_key: :id,
      inverse_of: :doctor,
      dependent: :destroy
    )

   has_many(
      :appointment_types,
      class_name: "AppointmentType",
      foreign_key: :doctor_id,
      primary_key: :id,
      inverse_of: :doctor,
      dependent: :destroy
    )

  has_many(
    :doctor_appointments,
    class_name: "Appointment",
    foreign_key: :doctor_id,
    primary_key: :id,
    inverse_of: :doctor,
    dependent: :destroy
  )



  def full_name
    return "#{self.first_name} #{self.last_name}"
  end

  def doctor_full_name
    # Should create a 'title column'
    return "Dr. #{self.first_name} #{self.last_name}"
  end

  def full_name_by_last
    return "#{self.last_name}, #{self.first_name}"
  end

  def patients_by_last_name
    self.patients.order(:last_name, :first_name)
  end

  ### Reminder Methods ###


  # returns AR relation of due reminders for a patient
  def due_reminders
    # self.reminders.select { |reminder| reminder.is_due? }
    self.reminders.where('datetime < ?', Time.zone.now)
  end
  
  def upcoming_reminders
    # self.reminders.select { |reminder| reminder.is_due? }
    self.reminders.where('datetime > ?', Time.zone.now)
  end

  # Returns all reminders that are not checked and are due by patient
  def incomplete_due_reminders
    # self.reminders.select { |reminder| (reminder.is_due? && !reminder.complete && !reminder.checked) }
    self.reminders.where('datetime < ? AND (complete IS NULL OR complete IS FALSE) AND checked IS FALSE', Time.zone.now)
  end

  def patients_reminders_by_type(type)
    self.patients.joins(:reminders).where("reminders.remindable_type = ? AND reminders.checked = ?", type, false).includes(:reminders)
  end

  def patients_with_reminders
    self.patients.includes(:reminders)
  end

  def patients_input_complete_unchecked_reminders
    self.patients.joins(:reminders).where("reminders.remindable_type = ? AND reminders.complete = ? AND reminders.input_checked = ?", "Input", true, false).includes(:reminders)
  end

  def incomplete_alerts
    self.patient_alerts.where("alerts.complete = ?", false)
  end

  def complete_alerts
    self.patient_alerts.where("alerts.complete = ?", true)
  end


  ### Alert Methods (for doctor)###

  def self.generate_all_alerts
    new_alert_count = 0

    self.where(is_doctor: true).joins(:patients).includes(:patients).each do |doctor|
      new_alert_count += doctor.generate_doctor_alerts
    end

    new_alert_count
  end

  # handle_asynchronously :generate_all_alerts

  def generate_doctor_alerts
    new_alert_count = 0
    new_alert_count += self.generate_missed_medication_alerts
    new_alert_count += self.generate_missed_appointment_alerts
    new_alert_count += self.generate_missed_input_alerts
    new_alert_count += self.generate_missed_treatment_alerts
    new_alert_count += self.generate_unhealthy_input_alerts

    new_alert_count
  end

  # handle_asynchronously :generate_doctor_alerts

  # TODO: Have TA check this on Monday // Make this run on all patients instead of patient's by doctor
  # TODO: Could generate 'reason' dynamically with a single helper method
  def generate_missed_medication_alerts
    patient_population = self.patients_reminders_by_type("medication")
    new_alert_count = 0

    patient_population.each do |patient|
      skipped_med_count = 0
      allowed_skipped = self.alert_setting.first.skipped_meds
      reminder_ids = []

      patient.incomplete_due_reminders.each do |reminder|
        if ((Time.zone.now - reminder.datetime) / 60 / 60) > 1
          skipped_med_count += 1
          reminder_ids << reminder.id
        end

        if skipped_med_count > allowed_skipped
          allowed_skipped *= 2

          current_alert = patient.alerts.build({
            alert_type: "medication",
            reminders_skipped: skipped_med_count,
            reason: "Skipped #{skipped_med_count} Meds"
          })

          patient.reminders.find(reminder_ids).each do |checked_reminder|
            checked_reminder.checked = true
            checked_reminder.save
          end

          new_alert_count += 1 if current_alert.save
        end
      end
    end

    new_alert_count
  end

  def generate_missed_appointment_alerts
    patient_population = self.patients_reminders_by_type("appointment")
    new_alert_count = 0

    patient_population.each do |patient|
      skipped_appointment_count = 0
      allowed_skipped = self.alert_setting.first.skipped_appointments
      reminder_ids = []

      patient.incomplete_due_reminders.each do |reminder|
        if ((Time.zone.now - reminder.datetime) / 60 / 60) > 1
          skipped_appointment_count += 1
          reminder_ids << reminder.id
        end

        if skipped_appointment_count > allowed_skipped
          allowed_skipped *= 2

          current_alert = patient.alerts.build({
            alert_type: "appointment",
            reminders_skipped: skipped_appointment_count,
            reason: "Skipped #{skipped_appointment_count} Appointments"
          })

          patient.reminders.find(reminder_ids).each do |checked_reminder|
            checked_reminder.checked = true
            checked_reminder.save
          end

          new_alert_count += 1 if current_alert.save
        end
      end
    end

    new_alert_count
  end

  # Tested
  def generate_missed_input_alerts
    patient_population = self.patients_reminders_by_type("input")
    new_alert_count = 0

    patient_population.each do |patient|
      skipped_input_count = 0

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_filter :require_doctor_status, :only => [:]
  # before_filter :require_signed_out!, :only => [:new, :create]
  before_filter :require_signed_in!, :only => [:show, :edit]
  before_filter :require_authority!, :only => [:show, :edit]

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(params[:user])
    @user.health.build()

    if current_user && current_user.is_doctor
      @user.doctor_id = current_user.id
    end

    if password_confirmed?
      flash.now[:errors] = ["Your passwords did not match!"]
      render :new
    elsif @user.save
      
      # Sends activation email
      UserMailer.activation_email(@user).deliver!
      sign_in(@user) unless current_user and current_user.is_doctor
      
      if current_user.is_doctor
        redirect_to doctor_url(current_user.id)
      else
        render :show
      end
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user]) && @user.health[0].update_attributes(params[:health])
      flash[:notices] = ["User Updated."]
      if has_doctor_authority?
        redirect_to doctor_url(@user)
      else
        redirect_to user_url(@user)
      end
    else
      flash.now[:errors] = @user.errors.full_messages
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def activate
    @user = User.find_by_activation_token(params[:activation_token])
    
    if params[:activation_token] && @user
      @user.activate!
      sign_in(@user)
      flash[:errors] =  ["Successfully activated your account!"]
      redirect_to @user
    else
      raise ActiveRecord::RecordNotFound.new()
    end
  end
  
 ## Moved to PasswordResetsController
 #  def password_reset
 #    
 #  end
 #  
 ## Moved to PasswordResetsController
 #  def password_update
 #    @user = User.find_by_activation_token(params[:activation_token])
 #    
 #    if password_confirmed?
 #      @user.password = params[:user][:password]
 #      
 #      if @user.save
 #        flash.now[:errors] = ["Password changed successfully!"]
 #        render :show
 #      else
 #        flash.now[:errors] = @user.errors.full_messages
 #        render
 #        redirect_to
 #      end
 #    else
 #      redirect_to
 #    end
 #  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
  <form class="form" action="<%= users_url %>" method="post">
    <%= auth_token %>
    <h3>New Patient</h3>

    <div class="input">
      <label for="first-name">First Name</label>
      <input id="first-name" type="text" name="user[first_name]" value="<%= @user.first_name %>">
    </div>

    <div class="input">
      <label for="last-name">Last Name</label>
      <input id="last-name" type="text" name="user[last_name]" value="<%= @user.last_name %>">
    </div>

    <div class="input">
      <label for="email">Email</label>
      <input id="email" type="email" name="user[email]" value="<%= @user.email %>">
    </div>

    <div class="input">
      <label for="password">Password</label>
      <input id="password" type="password" name="user[password]" value="">
    </div>

    <div class="input">
      <label for="password">Confirm Password</label>
      <input id="password" type="password" name="password" value="">
    </div>

    <div class="submit long-submit">
      <input type="submit" value="Sign Up">
    </div>
    
    <div class="google-signin">
      <a class="group" href="/auth/google_oauth2"></a>
    </div>
  </form>

app/views/users/_sub_bar.html.erb
<div class="sub-bar group">

  <div class="avatar">
    <%= image_tag user.avatar.url(:small) %>
  </div>

  <div class="nav-search group">
  </div>

  <div class="user-info group">
    <ul>
      <li><%= link_to user.full_name, user_url(user) %></li>
    </ul>
  </div>

  <div class="sub-nav">
    <ul>
      <li id=<%= 'icon-selected' if params[:controller] == "diagnoses" %>><a class="<%= 'green-' if params[:controller] == "diagnoses" %>diagnosis-icon icon" href="<%= user_diagnoses_url(user) %>">Dx</a></li>
      <li id=<%= 'icon-selected' if params[:controller] == "reminders" %>><a class="<%= 'green-' if params[:controller] == "reminders" %>reminder-icon icon" href="<%= user_reminders_url(user) %>">Reminders</a></li>
      <li id=<%= 'icon-selected' if params[:controller] == "appointments" %>><a class="<%= 'green-' if params[:controller] == "appointments" %>appointment-icon icon" href="<%= user_appointments_url(user)%>">Appointments</a></li>
      <li id=<%= 'icon-selected' if params[:controller] == "symptoms" %>><a class="<%= 'green-' if params[:controller] == "symptoms" %>treatment-icon icon" href="<%= user_symptoms_url(user) %>">Treatments</a></li>
      <li id=<%= 'icon-selected' if params[:controller] == "medications" %>><a class="<%= 'green-' if params[:controller] == "medications" %>medication-icon icon" href="<%= user_medications_url(user)%>">Medications</a></li>
      <li id=<%= 'icon-selected' if params[:controller] == "educations" %>><a class="<%= 'green-' if params[:controller] == "educations" %>education-icon icon" href="<%= %>">Education</a></li>
      <li id=<%= 'icon-selected' if params[:controller] == "patient_reports" %>><a class="<%= 'green-' if params[:controller] == "patient_reports" %>report-icon icon" href="<%= %>">Reports</a></li>
    </ul>
  </div>
</div>

<%= render "application/messages", message_type: "errors" %>  
<%= render "application/messages", message_type: "notices" %>

<% content_for :js do %>
  <script type="text/javascript">
    $(document).ready(function() {
    
      $('.sub-nav > ul > li').click(function(data) {
        $(data.currentTarget).attr("id", "icon-clicked");
        
      });
      
    });
  </script>

<% end %>

app/views/users/edit.html.erb
<% if current_user.is_doctor %>
  <%= render "doctors/sub_bar", doctor: @user%>
<% else %>
  <%= render "users/sub_bar", user: @user %>
<% end %>

<main class="group">
	
  <div class="side-content">
    <div class="title">
      <h3>User Settings</h3>
    </div>
  </div>
  
  <div class="sub-content">
    <form class="form" action="<%= user_url(@user) %>" method="POST" enctype="multipart/form-data">

      <h3>Settings:</h3>

      <input type="hidden" name="_method" value="PUT">
      <%= auth_token %>

      <div class="input">
        <label for="avatar">Photo:</label>
        <input id="avatar" type="file" name="user[avatar]" value="">
      </div>

      <div class="input">
        <label for="first-name">First Name</label>
        <input id="first-name" type="text" name="user[first_name]" value="<%= @user.first_name %>">
      </div>

      <div class="input">
        <label for="last-name">Last Name</label>
        <input id="last-name" type="text" name="user[last_name]" value="<%= @user.last_name %>">
      </div>

      <div class="input">
      <label for="height">Height (inches)</label>
        <select id="height" name="health[height]">
          <% 24..99.times do |i| %>
            <option <%= 'selected' if @user.health[0] && i == @user.health[0].height %> value="<%= i %>"><%= i %></option>
          <% end %>
        </select>
      </div>

      <div class="radio-group group">
        <label>Email Notifiations:</label>

          <div class="radio-input">
            <label for="on">On</label>
            <input id="on" type="radio" <%= "checked" if @user.email_notifications %> name="user[email_notifications]" value="true">
          </div>

          <div class="radio-input">
            <label for="off">Off</label>
              <input id="off" type="radio" <%= "checked" unless @user.email_notifications %> name="user[email_notifications]" value="false">
            </label>
          </div>
      </div>
      
      <div class="input">
        <label for="timezone">Timezone:</label>
        <select id="timezone" name="user[timezone]" style="width: 300px;">
          <% ActiveSupport::TimeZone.zones_map.each do |k, v| %>
            <option <%= "selected" if @user.timezone == k %> value="<%= k %>"><%= v %></option>
          <% end %>
        </select>
      </div>

      <div class="submit long-submit">
        <input type="submit" value="Save Settings">
      </div>
    </form>
	
  </div>
  
</main>

<% content_for :js do %>
  <script type="text/javascript">
    $(document).ready(function() {
      $('select#timezone').select2();
      
    });
  </script>

<% end %>

app/views/users/new.html.erb
<%= render "doctors/sub_bar", doctor: current_user if signed_in_doctor? %>

<main class="group">
  <div class="side-content">
    <div class="title">
      <% if current_user && current_user.is_doctor %>
        <h2>New Patient</h2>
      <% else %>
        <h3>New Patient User</h3>
      <% end %>
    </div>

    <h3><a href="/auth/google_oauth2">Login with Google</a></h3>
  </div>

  <div class="sub-content">
    <%= render partial: "form" %>
  </div>
</main>

app/views/users/show.html.erb
<%= render "sub_bar", user: @user%>

<main class="group">

  <div class="side-content">
    <div class="title">
      <h2>Patient:</h2>
    </div>
    <div class="side-info">
    <p><%= @user.full_name %></p>
  </div>

  </div>

  <div class="sub-content">
    <h3>Patient Details:</h3>
    <ul>
      <li>Email: <%= @user.email %></li>
      <li>Phone: <%= @user.phone %></li>
      <li>Height: <%= @user.health.empty? ? link_to("Not provided", edit_user_url(@user)) : @user.health[0].height %></li>
    </ul>
    <br><br><br><br>
  </div>

</main>