config/routes.rb
PreventIT::Application.routes.draw do
  get "password_resets/new"

  # get 'doctors/new', to: 'users#new_doctor'
#   post 'doctors', to: 'users#create_doctor'

  resources :doctors

  get '/search' => 'pages#new', as: 'new_search'
  get '/search/patients' => 'pages#search_patients', as: 'patient_search'
  get '/search/diagnoses' => 'pages#search_diagnoses', as: 'diagnoses_search'
  get '/search/medications' => 'pages#search_medications', as: 'medications_search'
  get '/search/full_medications' => 'pages#search_full_medications', as: 'full_medications_search'
  # get '/med_init_selection' => 'pages#init_selection', as: 'medication_init'
  get 'alerts/completed' => 'alerts#completed', as: 'alerts_completed'

  resources :alerts, only: [:index, :edit, :update, :show]
  resources :appointment_types

  put 'alert/:id/complete' => 'alerts#mark_complete', as: 'alert_complete'

  get 'users/:user_id/reminders/completed' => 'reminders#completed', as: 'reminders_completed'
  get 'users/:user_id/reminders/upcoming' => 'reminders#upcoming', as: 'reminders_upcoming'
  
  
  resources :users, only: [:create, :new, :destroy, :show, :edit, :update] do
    resources :reminders
    resources :diagnoses
    resources :appointments
    get 'add_diagnosis' => 'diagnoses#add_diagnosis', as: 'add_diagnosis'
    get :activate, on: :collection
    get :password_reset, on: :collection
    put :password_update, on: :collection
    resources :medications
    resources :symptoms do
      resources :reminders, controller: :reminders, only: [:new, :create, :index]
    end
  end
  
  resource :session, only: [:create, :destroy, :new]
  resources :password_resets, only: [:new, :edit, :update, :create]
  get '/auth/google_oauth2/callback' => 'sessions#create'

  root to: "sessions#new"
end

app/models/alert.rb
# == Schema Information
#
# Table name: alerts
#
#  id                :integer          not null, primary key
#  patient_id        :integer          not null
#  alert_type        :string(255)      not null
#  complete          :boolean          default(FALSE), not null
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  reminders_skipped :integer
#  reason            :string(255)
#

### ALERT TYPE is not a good way to design this. Alerts should instead be polymorphic like reminders.
class Alert < ActiveRecord::Base
  attr_accessible :patient, :patient_id, :alert_type, :complete, :reminders_skipped, :reason

  validates :patient, presence: true
  validates :alert_type, presence: true, inclusion: { in: %w(appointment medication treatment input), message: "Invalid type" }

  belongs_to(
    :patient,
    class_name: "User",
    foreign_key: :patient_id,
    primary_key: :id,
    inverse_of: :alerts
  )

  has_one(
    :doctor,
    through: :patient,
    source: :doctor
  )

  def complete_str
    (self.complete) ? "complete" : "incomplete"
  end
  
  def complete?
    self.complete
  end
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  before_filter :require_signed_in!
  before_filter :require_doctor_status!

  def index
    @doctor = current_user
    @alerts = @doctor.incomplete_alerts.page(params[:page]).per(20)
  end

  def completed
    @doctor = current_user
    @alerts = @doctor.complete_alerts.page(params[:page]).per(20)
  end

  def show
    @alert = Alert.find(params[:id])
    @patient = @alert.patient
  end

  def mark_complete
    @alert = Alert.find(params[:id])
    @alert.complete = true

    @alert.save

    redirect_to alerts_url
  end
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/views/alerts/_list.html.erb
<div class="reminders-table">
  <table id="alerts" class="alert-table">

    <thead>
      <tr>
        <th>Reason</th>
        <th>Type</th>
        <th>Date</th>
        <th>Time</th>
        <th>Patient</th>
        <th>Complete?</th>
      </tr>
    </thead>

    <% alerts.each do |alert| %>
      <tr>
        <td><%= link_to alert.reason, alert_url(alert) %></td>
        <td><%= alert.alert_type %></td>
        <td><%= alert.created_at.to_s(:date) %></td>
        <td><%= alert.created_at.to_s(:time_12hr) %></td>
        <td><%= link_to alert.patient.full_name, user_url(alert.patient) %></td>
        <td><%= alert.complete_str %></td>
      </tr>
    <% end %>

  </table>
</div>

app/views/alerts/completed.html.erb
<%= render "doctors/sub_bar", doctor: @doctor%>

<main class="group">
  <div class="side-content">
    <div class="title">
		<h3>Alerts:</h3>
	</div>

	<div class="side-info">
		<%= link_to "New Alerts", alerts_url %>
	</div>
  </div>

  <div class="sub-content">
    <label for="alerts" class="table-label">Old Alerts:</label>

    <%= render "list", alerts: @alerts %>
  </div>
</main>

app/views/alerts/index.html.erb
<%= render "doctors/sub_bar", doctor: @doctor%>

<main class="group">
  <div class="side-content">
    <div class="title">
      <h2>Alerts:</h2>
    </div>

	<div class="side-info">
		<%= link_to "Completed Alerts", alerts_completed_url %>
	</div>
  </div>


  <div class="sub-content">
   <label for="alerts" class="table-label">New Alerts:</label>

   <p><%= paginate @alerts %></p>

   <%= render "list", alerts: @alerts %>
   <p><%= paginate @alerts %></p>
  </div>

</main>

app/views/alerts/show.html.erb
<%= render "doctors/sub_bar", doctor: @patient.doctor%>

<main class="group">

  <div class="side-content">
    <div class="title">
      <h2>Alert Show</h2>
    </div>
    <div class="side-info">
      <ul>
        <li><%= link_to @patient.full_name, user_url(@patient) %></li>
        <li><%= @patient.phone %></li>
        <li><%= @patient.email %></li>
      </ul>
    </div>
    
    <div class="side-info">
      <ul>
        <li><%= link_to "Alerts", alerts_url %></li>
        <li><%= link_to "Completed", alerts_completed_url %></li>
      </ul>
    </div>
  </div>



  <div class="sub-content">
    <div class="reminders-table">
      <table id="incomplete_alerts" class="alert-table">
        <label for="incomplete_alerts" class="table-label">New Alerts:</label>
        <thead>
          <tr>
            <th>Reason</th>
            <th>Type</th>
            <th>Date</th>
            <th>Complete?</th>
          </tr>
        </thead>

        <tr>
          <td><%= @alert.reason %></td>
          <td><%= @alert.alert_type %></td>
          <td><%= @alert.created_at.to_formatted_s(:long_ordinal) %></td>
          <td><%= (@alert.complete) ? @alert.complete_str : button_to("Mark Complete", alert_complete_url(@alert), method: :put, class: "button green-button")  %></td>
        </tr>

      </table>
    </div>
  </div>
</main>