config/routes.rb
PreventIT::Application.routes.draw do
  get "password_resets/new"

  # get 'doctors/new', to: 'users#new_doctor'
#   post 'doctors', to: 'users#create_doctor'

  resources :doctors

  get '/search' => 'pages#new', as: 'new_search'
  get '/search/patients' => 'pages#search_patients', as: 'patient_search'
  get '/search/diagnoses' => 'pages#search_diagnoses', as: 'diagnoses_search'
  get '/search/medications' => 'pages#search_medications', as: 'medications_search'
  get '/search/full_medications' => 'pages#search_full_medications', as: 'full_medications_search'
  # get '/med_init_selection' => 'pages#init_selection', as: 'medication_init'
  get 'alerts/completed' => 'alerts#completed', as: 'alerts_completed'

  resources :alerts, only: [:index, :edit, :update, :show]
  resources :appointment_types

  put 'alert/:id/complete' => 'alerts#mark_complete', as: 'alert_complete'

  get 'users/:user_id/reminders/completed' => 'reminders#completed', as: 'reminders_completed'
  get 'users/:user_id/reminders/upcoming' => 'reminders#upcoming', as: 'reminders_upcoming'
  
  
  resources :users, only: [:create, :new, :destroy, :show, :edit, :update] do
    resources :reminders
    resources :diagnoses
    resources :appointments
    get 'add_diagnosis' => 'diagnoses#add_diagnosis', as: 'add_diagnosis'
    get :activate, on: :collection
    get :password_reset, on: :collection
    put :password_update, on: :collection
    resources :medications
    resources :symptoms do
      resources :reminders, controller: :reminders, only: [:new, :create, :index]
    end
  end
  
  resource :session, only: [:create, :destroy, :new]
  resources :password_resets, only: [:new, :edit, :update, :create]
  get '/auth/google_oauth2/callback' => 'sessions#create'

  root to: "sessions#new"
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_filter :require_signed_in!, :only => [:show, :edit]
  before_filter :require_doctor_authority!, :only => [:show, :edit]

  def new
    @practice = Practice.new
    @user = @practice.doctors.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @practice = Practice.new(params[:practice])
    @user = @practice.doctors.build(params[:user])
    @user.is_doctor = true
    @user.alert_setting.build

    if params[:password] != params[:user][:password]
      flash.now[:errors] = ["Your passwords did not match!"]
      render :new
    elsif @practice.save
      sign_in(@user)
      redirect_to doctor_url(@user)
    else
      flash.now[:errors] = @practice.errors.full_messages
      render :new
    end
  end

  def show
    @doctor = User.includes(:patients).find(params[:id])
    @patients = current_user.patients_by_last_name.page(params[:page])
    render :show
  end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_sub_bar.html.erb
<div class="sub-bar group">

  <div class="avatar">
    <%= image_tag current_user.avatar.url(:small) %>
  </div>

  <div class="nav-search group">
    <%= render "pages/nav_search" %>
  </div>

  <div class="user-info">
    <ul>
      <li><%= link_to "Total Patients: #{current_user.patients.count}", doctor_url(current_user) %></li>
    </ul>
  </div>

  <div class="sub-nav">
    <ul>
      <li id=<%= 'icon-selected' if params[:controller] == "alerts" %>><a class="<%= 'green-' if params[:controller] == "alerts" %>alert-icon icon group" href="<%= alerts_url %>">Alerts<strong class="counter-badge"><%= doctor.incomplete_alerts.count %></strong></a></li>
      <li id=<%= 'icon-selected' if params[:controller] == "appointment_types" %>><a class="<%= 'green-' if params[:controller] == "appointment_types" %>appointment-type-icon icon" href="<%= appointment_types_url %>">Types</a></li>
      <li id=<%= 'icon-selected' if params[:controller] == "goals" %>><a class="<%= 'green-' if params[:controller] == "goals" %>goal-icon icon" href="<%= %>">Goals</a></li>
      <li id=<%= 'icon-selected' if params[:controller] == "practice_reports" %>><a class="<%= 'green-' if params[:controller] == "practice_reports" %>report-icon icon" href="<%= %>">Reports</a></li>
    </ul>
  </div>
</div>

<%= render "application/messages", message_type: "errors" %>  
<%= render "application/messages", message_type: "notices" %>

<% content_for :js do %>
  <script type="text/javascript">
    $(document).ready(function() {
    
      $('.sub-nav > ul > li').click(function(data) {
        $(data.currentTarget).attr("id", "icon-clicked");
        
      });
      
    });
  </script>

<% end %>

app/views/doctors/new.html.erb
<main class="group">
  <form class="form" action="<%= doctors_url %>" method="post">
    <%= auth_token %>

    <h2>New Doctor</h2>
    <div class="input">
      <label for="practice-name">Practice Name:</label>
      <input id="practice-name" type="text" name="practice[name]" value="<%= @practice.name %>">
    </div>

    <div class="input">
      <label for="practice-specialty">Specialty:</label>
      <input id="practice-specialty" type="text" name="practice[specialty]" value="<%= @practice.specialty %>">
    </div>

    <div class="input">
      <label for="first-name">First Name</label>
      <input id="first-name" type="text" name="user[first_name]" value="<%= @user.first_name %>">
    </div>

    <div class="input">
      <label for="last-name">Last Name</label>
      <input id="last-name" type="text" name="user[last_name]" value="<%= @user.last_name %>">
    </div>

    <div class="input">
      <label for="email">Email</label>
      <input id="email" type="text" name="user[email]" value="<%= @user.email %>">
    </div>

    <div class="input">
      <label for="password">Password</label>
      <input id="password" type="password" name="user[password]" value="">
    </div>

    <div class="input">
      <label for="password">Confirm Password</label>
      <input id="password" type="password" name="password" value="">
    </div>

    <div class="submit long-submit">
      <input type="submit" value="Doctor Sign Up">
    </div>
  </form>
</main>

app/views/doctors/show.html.erb
<%= render "sub_bar", doctor: @doctor%>

<main class="group">


  <div class="side-content">
    <div class="title">
      <h3>Doctor Page</h3>
    </div>
    <div class="side-info">
      <a href="<%= new_user_url %>">Add New Patient</a>
    </div>
  </div>

  <div class="sub-content">

    <h3><%= @doctor.practice.name %> Patients: (Total: <%= @doctor.patients.count %>)</h3>

    <p><%= paginate @patients %></p>

    <ul>
      <% @patients.each do |patient| %>
        <li><%= link_to patient.full_name_by_last, user_url(patient) %></li>
      <% end %>
    </ul>

    <p><%= paginate @patients %></p>

  </div>

</main>